version: '3.9'

services:
  oa-redis:
    image: redis:6.2.0-alpine
    volumes:
      - ./redis-config:/usr/local/etc/redis
    ports:
      - "6379:6379"
  courier-redis:
    image: redis:6.2.0-alpine
    volumes:
      - ./redis-config:/usr/local/etc/redis
    command: --port 6380
    ports:
      - "6380:6380"
  sqs:
    image: roribio16/alpine-sqs
    container_name: sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./config/elasticmq.conf:/opt/config/elasticmq.conf
  sns:
    image: s12v/sns
    container_name: sns
    ports:
      - "9911:9911"
    volumes:
      - ./config/db.json:/etc/sns/db.json
    depends_on:
      - sqs
  oa-service:
    image: orderassignmentservice:0.1.0-SNAPSHOT
    container_name: order-assignment-service
    ports:
      - "9060:9060"
    depends_on:
      - sqs
      - sns
      - oa-redis
  courier-service:
    image: courierservice:0.1.0-SNAPSHOT
    container_name: courier-service
    ports:
      - "9070:9070"
    depends_on:
      - sqs
      - sns
      - courier-redis